from pathlib import Path


class GRDECLWriter:

    def __init__(self, model):
        self.model = model

    def write(self, filename=None):

        if filename is None:
            filename = self.model.name + ".GRDECL"

        with open(filename, "w") as f:

            f.write("-- Generated by PyGRID\n")
            f.write("\n")

            f.write("SPECGRID\n")
            f.write(
                f"  {self.model.nx} {self.model.ny} {self.model.layers} 1 F /\n\n"
            )

            f.write("-- COORD\n")
            f.write("-- not implemented yet\n\n")

            f.write("COORD\n")
            f.write("/\n\n")

            f.write("ZCORN\n")
            f.write("/\n")