from .faults import FaultSet
from .grdecl import GRDECLWriter
from .maps import ContourMap, ThicknessMap


class GridModel:

    def __init__(
        self,
        name,
        units,
        xmin,
        ymin,
        xmax,
        ymax,
        nx,
        ny,
    ):
        self.name = name
        self.units = units
        # TinyECL may define horizontal/surface units and depth units separately.
        self.surface_units = units
        self.depth_units = units
        self.xmin = xmin
        self.ymin = ymin
        self.xmax = xmax
        self.ymax = ymax
        self.nx = nx
        self.ny = ny

        self.extent = None
        self.top = None
        self.bottom = None
        self.thickness = None
        # Optional thickness-derived internal structural horizon.
        # FROM_TOP means MID = TOP + THICKNESS.
        self.thickness_mode = None
        self.thickness_split_layer = 0
        self.top_faults = None
        self.bottom_faults = None
        self.wells = None
        self.layer_mode = None
        self.layers = None
        self.layer_thicknesses = None
        # Structural zones may pinch out where interpreted horizons meet/cross.
        # Zero matches TinyECL/tNavigator's current minimum-zone-thickness use.
        self.minimum_zone_thickness = 0.0
        self.angle = 0
        self.rotation_center = None
        self.split_faults = False
        # Keep v3 interpolation behaviour.  Smoothing is applied only after
        # the first (top) ZCORN interface has been created.
        self.search_radius = None
        self.smoothing_method = "LAPLACIAN"
        self.smooth_iterations = 0
        self.smooth_factor = 0.15
        # Taubin's second (inflation) pass.  None means use -1.05 * smooth_factor.
        self.smooth_taubin_mu = None
        # Bilateral Z scale.  None chooses a robust value automatically from
        # connected-neighbour depth differences.
        self.smooth_bilateral_sigma_z = None
        # Biharmonic curvature penalty. None derives it from iterations*factor.
        self.smooth_biharmonic_lambda = None
        self.fault_set = FaultSet()
        self._last_fault_faces = []

    def rotate(self, angle, x, y):
        self.angle = angle
        self.rotation_center = (x, y)

    def read_maps(self):
        if self.top:
            self.top_map = ContourMap(self.top).read()
        if self.bottom:
            self.bottom_map = ContourMap(self.bottom).read()
        if self.thickness:
            self.thickness_map = ThicknessMap(self.thickness).read()

    def read_faults(self):
        if self.split_faults and self.top_faults:
            self.fault_set = FaultSet.from_tinyecl(
                self.top_faults,
                self.bottom_faults,
            )
        else:
            self.fault_set = FaultSet()

    def write_grdecl(self, specgrid=True, coord=True, zcorn=True):
        self.read_maps()
        self.read_faults()

        writer = GRDECLWriter(self)
        writer.write(specgrid=specgrid, coord=coord, zcorn=zcorn)
        self._last_fault_faces = writer.fault_faces()

    def write_faults(self, filename):
        # If write_faults is called separately, make sure geometry exists.
        if self.split_faults and not self.fault_set:
            self.read_faults()

        faces = self._last_fault_faces
        if self.split_faults and not faces:
            writer = GRDECLWriter(self)
            faces = writer.fault_faces()

        with open(filename, "w", encoding="utf-8") as f:
            f.write("-- Generated by PyGRID\n\n")
            f.write("FAULTS\n")
            f.write("-- NAME IX1 IX2 IY1 IY2 IZ1 IZ2 FACE\n")
            for name, i, j, face in faces:
                f.write(
                    f"  '{name}' {i} {i} {j} {j} "
                    f"1 {self.layers} '{face}' /\n"
                )
            f.write("/\n")
