from .grdecl import GRDECLWriter

from pathlib import Path

from .maps import ContourMap, ThicknessMap


class GridModel:

    def __init__(
        self,
        name,
        units,
        xmin,
        ymin,
        xmax,
        ymax,
        nx,
        ny
    ):

        self.name=name
        self.units=units

        self.xmin=xmin
        self.ymin=ymin
        self.xmax=xmax
        self.ymax=ymax

        self.nx=nx
        self.ny=ny


        self.extent=None

        self.top=None
        self.bottom=None
        self.thickness=None

        self.top_faults=None
        self.bottom_faults=None

        self.wells=None

        self.layer_mode=None
        self.layers=None

        self.angle=0


    def rotate(self, angle, x, y):

        self.angle=angle
        self.rotation_center=(x,y)


    def read_maps(self):

        if self.top:

            self.top_map=ContourMap(
                self.top
            ).read()


        if self.bottom:

            self.bottom_map=ContourMap(
                self.bottom
            ).read()


        if self.thickness:

            self.thickness_map=ThicknessMap(
                self.thickness
            ).read()

            
    def write_grdecl(
        self,
        specgrid=True,
        coord=True,
        zcorn=True,
    ):

        self.read_maps()

        writer = GRDECLWriter(self)

        writer.write()

        
    def write_faults(self, filename):

        with open(filename, "w") as f:

            f.write("-- Generated by PyGRID\n")
            f.write("-- Fault output not implemented yet\n")
